-- 一期知识资产目录种子（≥20 条，INSERT IGNORE 可重复执行）
-- 执行前需已应用 migrations/006 与 009（gateway_knowledge_assets 含扩展列）

INSERT IGNORE INTO `gateway_knowledge_assets`
  (`asset_key`, `name`, `asset_type`, `asset_category`, `status`, `source_uri`, `domain`, `module`, `version`, `owner`, `metadata_json`)
VALUES
  ('ka-wiki-gateway-evolution', 'AI工程化管理系统-gateway演进方案', 'markdown', '规范类', 'active', 'projects/wiki/技术中心-2026Q2-AI工程化管理系统-基于gateway数据库资产演进方案.md', 'platform', 'control-plane', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_core','gate_ref', true)),
  ('ka-wiki-harness-plan', 'Harness工程化项目落地方案', 'markdown', '规范类', 'active', 'projects/wiki/技术中心-2026Q2-AI组织能力升级-Harness工程化项目落地方案.md', 'platform', 'harness', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_core')),
  ('ka-wiki-org-upgrade', '购商云汇AI组织能力升级汇报', 'markdown', '规范类', 'active', 'projects/wiki/购商云汇2026年产品研发体系AI组织能力升级汇报.md', 'org', 'pmo', '1.0', 'PMO', JSON_OBJECT('ingest_rule','wiki_core')),
  ('ka-prd-sales-order', '销售订单详细PRD样板', 'markdown', '样板类', 'active', 'projects/ai-platform/docs/销售订单详细PRD.md', 'sales', 'order', '1.0', '产品组', JSON_OBJECT('node_ref','std_prd_gate','spot_check','required')),
  ('ka-arch-overview', '平台架构说明', 'markdown', '规范类', 'active', 'projects/ai-platform/docs/architecture.md', 'platform', 'all', '1.0', '架构组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-deploy-runbook', '部署说明', 'markdown', '模板类', 'active', 'projects/ai-platform/docs/deployment.md', 'ops', 'deploy', '1.0', '运维组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-eng-mgmt-evolution', '工程化管理演进', 'markdown', '规范类', 'active', 'projects/ai-platform/docs/engineering-management-evolution.md', 'platform', 'governance', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-gate-prd-yaml', 'PRD门禁YAML规则', 'yaml', '提示词/规则类', 'active', 'projects/ai-platform/gate-engine/rules/prd-gate.yaml', 'gate', 'prd', '1.0', '平台组', JSON_OBJECT('gate_engine_ref', true, 'sync_note','see docs/GATE_RULE_SOURCE_OF_TRUTH.md')),
  ('ka-gate-tech-yaml', '技术方案门禁YAML规则', 'yaml', '提示词/规则类', 'active', 'projects/ai-platform/gate-engine/rules/tech-gate.yaml', 'gate', 'tech', '1.0', '平台组', JSON_OBJECT('gate_engine_ref', true)),
  ('ka-gate-code-yaml', '代码门禁YAML规则', 'yaml', '提示词/规则类', 'active', 'projects/ai-platform/gate-engine/rules/code-gate.yaml', 'gate', 'code', '1.0', '平台组', JSON_OBJECT('gate_engine_ref', true)),
  ('ka-client-matrix', '客户端接入矩阵与统一拦截', 'markdown', '规范类', 'active', 'projects/ai-platform/docs/客户端接入矩阵与统一拦截方案.md', 'platform', 'gateway', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-openclaw-integration', 'OpenClaw集成方案', 'markdown', '规范类', 'active', 'projects/ai-platform/docs/OpenClaw 集成方案.md', 'integration', 'openclaw', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-readme-platform', 'ai-platform README', 'markdown', '模板类', 'active', 'projects/ai-platform/README.md', 'platform', 'root', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-usage-readme', '使用说明', 'markdown', '模板类', 'active', 'projects/ai-platform/使用说明.md', 'platform', 'onboarding', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-usage-log-user-id', '用量日志 user_id 说明', 'markdown', '规范类', 'active', 'projects/ai-platform/ai-gateway/docs/USAGE_LOG_USER_ID.md', 'platform', 'usage', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-kb-readme', '知识库服务 README', 'markdown', '规范类', 'active', 'projects/ai-platform/knowledge-base/README.md', 'rag', 'knowledge-base', '1.0', '平台组', JSON_OBJECT('phase2_rag', true)),
  ('ka-admin-ui-readme', '管理台 README', 'markdown', '模板类', 'active', 'projects/ai-platform/admin-ui/README.md', 'ui', 'admin-ui', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-openclaw-config', 'OpenClaw配置指南', 'markdown', '规范类', 'active', 'projects/ai-platform/docs/openclaw-配置指南.md', 'integration', 'openclaw', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-api-md', 'API文档', 'markdown', 'DDL/接口契约类', 'active', 'projects/ai-platform/docs/api.md', 'platform', 'api', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-optimization-summary', '优化实现总结', 'markdown', '样板类', 'active', 'projects/ai-platform/优化实现总结.md', 'platform', 'retro', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_ok')),
  ('ka-platform-manual', '平台使用手册', 'markdown', '规范类', 'active', 'projects/ai-platform/docs/platform-user-manual.md', 'platform', 'manual', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','platform_seed', true)),
  ('ka-doc-pipeline-guide', '文档管道使用说明', 'markdown', '规范类', 'active', 'projects/ai-platform/docs/E2E_SALES_ORDER_DOC_GATES.md', 'platform', 'doc-pipeline', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','node_ref','std_input_contract')),
  ('ka-test-plan-template-spec', '测试方案模板规范', 'markdown', '模板类', 'active', 'projects/ai-platform/docs/test-plan-template-spec.md', 'test', 'template', '1.0', '测试组', JSON_OBJECT('ingest_rule','platform_core','node_ref','std_test_plan_generate')),
  ('ka-test-plan-gate-rules', '测试方案门禁规则说明', 'markdown', '提示词/规则类', 'active', 'projects/ai-platform/docs/test-plan-gate-rules.md', 'test', 'gate', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','node_ref','std_test_plan_gate')),
  ('ka-runtime-observability-guide', '运行编排与可观测说明', 'markdown', '规范类', 'active', 'projects/ai-platform/docs/runtime-observability-guide.md', 'platform', 'runtime', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core')),
  ('ka-knowledge-audit-guide', '知识与审计运营说明', 'markdown', '规范类', 'active', 'projects/ai-platform/docs/knowledge-audit-guide.md', 'platform', 'knowledge', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core')),
  ('ka-metrics-acceptance-guide', '度量与阶段验收口径说明', 'markdown', '规范类', 'active', 'projects/ai-platform/docs/metrics-acceptance-guide.md', 'platform', 'acceptance', '1.0', 'PMO', JSON_OBJECT('ingest_rule','platform_core')),
  ('ka-harness-official-plan-local', 'Harness工程化项目落地方案（官方说明）', 'markdown', '规范类', 'active', 'docs/harness-feishu-integration-design.md', 'platform', 'harness', '1.0', '平台组', JSON_OBJECT('ingest_rule','wiki_core','official_source', true)),
  ('ka-ai-rules-readme', 'ai-rules 目录说明', 'markdown', '规范类', 'active', 'projects/ai-platform/ai-rules/README.md', 'platform', 'ai-rules', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','foundation_asset', true)),
  ('ka-ai-manual-pm-v1', 'AI 工作手册 PM V1.0', 'markdown', '规范类', 'active', 'projects/ai-platform/ai-rules/rules/ai-work-manual-pm-v1.md', 'product', 'manual', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','foundation_asset', true)),
  ('ka-ai-manual-rd-v1', 'AI 工作手册 RD V1.0', 'markdown', '规范类', 'active', 'projects/ai-platform/ai-rules/rules/ai-work-manual-rd-v1.md', 'engineering', 'manual', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','foundation_asset', true)),
  ('ka-ai-manual-qa-v1', 'AI 工作手册 QA V1.0', 'markdown', '规范类', 'active', 'projects/ai-platform/ai-rules/rules/ai-work-manual-qa-v1.md', 'test', 'manual', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','foundation_asset', true)),
  ('ka-ai-prompt-gate-review-agent', '门禁评审 Agent Prompt', 'markdown', '提示词/规则类', 'active', 'projects/ai-platform/ai-rules/prompts/gate-review-agent.md', 'platform', 'ai-rules', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core')),
  ('ka-ai-prompt-harness-node-executor', 'Harness 节点执行器 Prompt', 'markdown', '提示词/规则类', 'active', 'projects/ai-platform/ai-rules/prompts/harness-node-executor.md', 'platform', 'ai-rules', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core')),
  ('ka-ai-skill-p01-bug-analysis', 'P01 Bug 分析技能包', 'markdown', '提示词/规则类', 'active', 'projects/ai-platform/ai-rules/skills/p01-bug-analysis.md', 'engineering', 'p01', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core')),
  ('ka-ai-skill-p05-value-assessment', 'P05 价值初评技能包', 'markdown', '提示词/规则类', 'active', 'projects/ai-platform/ai-rules/skills/p05-value-assessment.md', 'product', 'p05', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core')),
  ('ka-ai-contract-node-input', '通用节点输入契约', 'json', 'DDL/接口契约类', 'active', 'projects/ai-platform/ai-rules/contracts/pipeline_node_input.schema.json', 'runtime', 'contract', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core')),
  ('ka-ai-contract-node-output', '通用节点输出契约', 'json', 'DDL/接口契约类', 'active', 'projects/ai-platform/ai-rules/contracts/pipeline_node_output.schema.json', 'runtime', 'contract', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core')),
  ('ka-ai-contract-value-assessment', '价值初评记录契约', 'json', 'DDL/接口契约类', 'active', 'projects/ai-platform/ai-rules/contracts/value_assessment_record.schema.json', 'product', 'contract', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core')),
  ('ka-ai-pipeline-p01', 'P01 技术管道模板', 'json', '规范类', 'active', 'projects/ai-platform/ai-rules/pipelines/p01-tech-bug-loop-v1.json', 'engineering', 'pipeline', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','pipeline_ref','p01-tech-bug-loop-v1')),
  ('ka-ai-pipeline-p02', 'P02 测试管道模板', 'json', '规范类', 'active', 'projects/ai-platform/ai-rules/pipelines/p02-test-automation-v1.json', 'test', 'pipeline', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','pipeline_ref','p02-test-automation-v1')),
  ('ka-ai-pipeline-p03', 'P03 运维管道模板', 'json', '规范类', 'active', 'projects/ai-platform/ai-rules/pipelines/p03-ops-release-closure-v1.json', 'ops', 'pipeline', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','pipeline_ref','p03-ops-release-closure-v1')),
  ('ka-ai-pipeline-p04', 'P04 项管管道模板', 'json', '规范类', 'active', 'projects/ai-platform/ai-rules/pipelines/p04-pm-task-closure-v1.json', 'pm', 'pipeline', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','pipeline_ref','p04-pm-task-closure-v1')),
  ('ka-ai-pipeline-p05', 'P05 产品价值初评模板', 'json', '规范类', 'active', 'projects/ai-platform/ai-rules/pipelines/p05-product-value-evaluation-v1.json', 'product', 'pipeline', '1.0', '平台组', JSON_OBJECT('ingest_rule','platform_core','pipeline_ref','p05-product-value-evaluation-v1'));
